# Dependabot configuration file
# See: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check for updates on Monday
      day: "monday"
    # Group all minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Limit pull requests to maximum 10 open at a time
    open-pull-requests-limit: 10
    # Labels on pull requests
    labels:
      - "dependencies"
      - "npm"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all updates together
    groups:
      github-actions:
        patterns:
          - "*"
    # Limit pull requests
    open-pull-requests-limit: 10
    # Labels on pull requests
    labels:
      - "dependencies"
      - "github-actions"
